### ISSUE TITLE
응용 프로그램 원인

### ISSUE THREAD

**Issue by MisooKim2** [mountain-ha/C202309#3]
산하 학생 안녕하세요.
수업 중에 응용 프로그램 에러가 떠서 제대로 해결하지 못했었죠?
해당 문제는 아래 코드로 인해 발생합니다.

**%nlf**의 의도가 아마도 double 자료형의 서식지정자로 쓰신 것 같은데요.
여기서 n은 실제 n을 입력하는 것이 아니라 실수의 소수 자릿수를 결정하기 위한 것입니다.
하여 올바르게 작성하시려면 **%.3lf** 이나 혹은 3을 다른 숫자로 바꿔서 작성하시면 됩니다.
이것 저것 바꿔가면 테스트 해보시면서 숙지하시길 바랍니다. 

https://github.com/mountain-ha/C202309/blob/086464949871c090e4d9da20d2db9b2b7d113e79/challenge/week6/studentGrade.c#L40

**Comment by mountain-ha** [comment]
응용 프로그램 원인 #3 해결 했습니다
