### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [mountain-ha/C202309#4]
#### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week4/pyramidReverse
    - Warning: data argument not used by format string [line 16]
    - Warning: data argument not used by format string [line 22]
        - 위 라인에서 printf에 출력할 변수가 입력되었으나 서식지정자가 없습니다.
        - printf("문자열", k++) 코드에서 printf는 , 뒤에 있는 변수값들을 출력하려고 하기 때문에, k++을 printf에서 빼거나 printf문에 k++의 결과를 출력할 서식 지정자를 추가해주세요.
- WARNING in challenge/week6/studentGrade
    - Warning: non-void function does not return a value [line 37]
    - Warning: non-void function does not return a value [line 41]
        -  위 라인에 함수에 반환형이 void가 아닌데 return 값이 없습니다. return 값을 추가하거나, 함수의 반환형을 void로 변경하세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/do-while_even

**Comment by mountain-ha** [comment]
20231031 중간 이전 전체 검토 결과 #4 수정 완료했습니다
